Algoritmo "Atividade 18"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/08/2024
Var
// Seção de Declarações das variáveis 
   n,resto: inteiro


inicio
   escreva ("Digite um número inteiro: ")
   leia (n)

   resto := n%2

   escreva ("O resto da divisão de ",n, " por 2 é: ",resto)


fimalgoritmo

fimalgoritmo


Fimalgoritmo